package com.cloudSavvy.utils;

import com.cloudSavvy.aws.common.IssueSeverity;
import com.cloudSavvy.common.IssueData;
import com.cloudSavvy.reporting.builder.GenerateReportInput;
import com.cloudSavvy.aws.common.EntityLinks;
import com.cloudSavvy.aws.common.EntityType;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.utils.StringUtils;

public class HtmlReportUtils {
    public static final String REGION_HEADER_START = "<h3>";
    public static final String REGION_HEADER_END = "</h3>";
    public static final String SECTION_HEADER_START = "<h4>";
    public static final String SECTION_HEADER_END = "</h4>";

    public static void appendResultHead(final StringBuilder sb) {
        sb.append("<html>");
        sb.append("<head>");
        sb.append("<meta charset=\"UTF-8\"/>");
        sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes\" />");
        sb.append("<style>");
        sb.append("body{margin:0;padding:0;background-color:#f4f5f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;font-size:14px;color:#1a202c;}");
        sb.append(".wrap{max-width:700px;margin:0 auto;background:#ffffff;}");
        sb.append(".hdr{background-color:#1a2332;padding:24px 32px;text-align:center;}");
        sb.append(".hdr-title{margin:0 0 5px;color:#FF9900;font-size:22px;font-weight:700;letter-spacing:1px;}");
        sb.append(".hdr-sub{margin:0;color:#a0aec0;font-size:12px;}");
        sb.append(".body{padding:24px 32px;}");
        sb.append("h2{margin:16px 0 10px;font-size:15px;font-weight:700;color:#1a2332;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #FF9900;padding-bottom:7px;text-align:left;}");
        sb.append("h3{margin:18px 0 6px;font-size:13px;font-weight:700;color:#FF9900;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-left:3px solid #FF9900;padding-left:10px;}");
        sb.append("h4{margin:10px 0 3px;font-size:14px;font-weight:600;color:#1a202c;padding:8px 12px;background-color:#f8fafc;border-left:3px solid #FF9900;}");
        sb.append(".issueDetails{margin:4px 0 4px 14px;font-size:13px;color:#4a5568;}");
        sb.append("ul{margin:4px 0 10px;padding-left:28px;}");
        sb.append("li{margin:4px 0;font-size:13px;}");
        sb.append("a{color:#2b6cb0;text-decoration:none;}");
        sb.append(".new-badge{background-color:#e53e3e;color:#fff;font-size:10px;font-weight:700;padding:1px 7px;border-radius:10px;margin-left:6px;}");
        sb.append(".sev-high{background-color:#e53e3e;color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:3px;}");
        sb.append(".sev-med{background-color:#dd6b20;color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:3px;}");
        sb.append(".sev-low{background-color:#38a169;color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:3px;}");
        sb.append(".sectionLine{border:none;border-top:1px solid #e2e8f0;margin:18px 0;}");
        sb.append(".shortLine{border:none;border-top:1px dashed #e2e8f0;margin:14px 0;}");
        sb.append(".centerText{text-align:center;color:#4a5568;margin:0 0 8px;}");
        sb.append(".settings{background-color:#f8fafc;border:1px solid #e2e8f0;padding:16px 20px;margin:14px 0;}");
        sb.append(".settings p{margin:6px 0;font-size:13px;color:#4a5568;}");
        sb.append("table{border-collapse:collapse;width:100%;}");
        sb.append("th{background-color:#2d3748;color:#fff;padding:10px 14px;text-align:left;font-size:13px;font-weight:600;}");
        sb.append("td{padding:9px 14px;border-bottom:1px solid #e2e8f0;font-size:13px;}");
        sb.append("tr:nth-child(even) td{background-color:#f8fafc;}");
        sb.append(".footer{background-color:#1a2332;padding:14px 32px;text-align:center;color:#718096;font-size:11px;}");
        sb.append("</style>");
        sb.append("</head>");
        sb.append("<body style=\"margin:0;padding:0;background-color:#f4f5f7;\">");
        sb.append("<div class=\"wrap\" style=\"max-width:700px;margin:0 auto;background:#ffffff;\">");
        sb.append("<div class=\"hdr\" style=\"background-color:#1a2332;padding:24px 32px;text-align:center;\">");
        sb.append("<p class=\"hdr-title\" style=\"margin:0 0 5px;color:#FF9900;font-size:22px;font-weight:700;\">CloudSavvy</p>");
        sb.append("<p class=\"hdr-sub\" style=\"margin:0;color:#a0aec0;font-size:12px;\">AWS Cost Optimization Report</p>");
        sb.append("</div>");
        sb.append("<div class=\"body\" style=\"padding:24px 32px;\">");
    }

    public static void appendTail(final StringBuilder sb) {
        sb.append("</div>"); // close .body
        sb.append("<div class=\"footer\" style=\"background-color:#1a2332;padding:14px 32px;text-align:center;color:#718096;font-size:11px;\">Generated by CloudSavvy &mdash; AWS Cost Optimization</div>");
        sb.append("</div>"); // close .wrap
        sb.append("</body>");
        sb.append("</html>");
    }

    public static String buildAnchorLink(final String link, final String text) {
        return String.format("<a href=\"%1$s\">%2$s</a>", link, text);
    }

    public static String buildResourceRow(Region region, EntityType entityType, String resourceId) {
        String link = EntityLinks.getEntityLink(region, entityType, resourceId);
        if (!StringUtils.isEmpty(link)) {
            return buildAnchorLink(link, resourceId);
        } else {
            return resourceId;
        }
    }

    public static String buildResourceRow(Region region, IssueData issueData) {
        String link;
        if (issueData.getEntityType().isContainer()) {
            link = EntityLinks.getEntityLink(region, issueData.getEntityType(),
                    issueData.getContainerName(), issueData.getEntityName());
        } else {
            link = EntityLinks.getEntityLink(region, issueData.getEntityType(), issueData.getEntityName());
        }

        if (!StringUtils.isEmpty(link)) {
            return buildAnchorLink(link, issueData.getEntityName());
        } else {
            return issueData.getEntityName();
        }
    }

    public static String buildRegionText(Region region) {
        return "<hr class=\"shortLine\" />"
                + REGION_HEADER_START + "Region: " + region.id() + REGION_HEADER_END;
    }

    public static String buildColumnText(String text) {
        return "<td>".concat(text).concat("</td>");
    }

    public static String buildHeaderCell(String text) {
        return "<th>".concat(text).concat("</th>");
    }

    public static String buildSeverityBadge(IssueSeverity severity) {
        String cssClass = switch (severity) {
            case HIGH -> "sev-high";
            case MEDIUM -> "sev-med";
            case LOW -> "sev-low";
        };
        return String.format("<span class=\"%s\">%s</span>", cssClass, severity);
    }

    public static String buildRunSettingsText(GenerateReportInput input, String allResourcesLink,
                                              String estimatedChargesLink) {
        StringBuilder sb = new StringBuilder();
        sb.append("<hr class=\"sectionLine\" />");
        sb.append("<h2>Analysis Settings</h2>");
        sb.append("<div class=\"settings\">");
        sb.append("<p><b>Analyzed Regions:</b> ").append(input.getAnalyzedRegions()).append("</p>");
        if (!StringUtils.isEmpty(input.getExecutionInput().getAwsAccountId())) {
            sb.append("<p><b>AWS Account Id:</b> ").append(input.getExecutionInput().getAwsAccountId()).append("</p>");
        }
        sb.append("<p><b>Analysis Time:</b> ").append(TimeUtils.getUserFormattedCurrentTime()).append("</p>");
        if (!StringUtils.isEmpty(allResourcesLink)) {
            sb.append("<p>").append(buildAnchorLink(allResourcesLink, "Analyzed Resources")).append("</p>");
        }
        if (!StringUtils.isEmpty(estimatedChargesLink)) {
            sb.append("<p>").append(buildAnchorLink(estimatedChargesLink, "Estimated Charges For AWS Services")).append("</p>");
        }
        sb.append("</div>");
        return sb.toString();
    }
}
